//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodspotting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int RecId { get; set; }
        public int ReId { get; set; }
        public string category { get; set; }
        public string Name { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
